### ISSUE TITLE
I tried a different approach and its working on my machine but not on the online platform.

### ISSUE THREAD

**Issue by IVRANUBHV** [dvkcool/competitive#1]
#include <bits/stdc++.h>
using namespace std;
int main()
{ int t;
cin>>t;
 while(t>0)
 {  t--;
    int n,k;
    cin>>n>>k;
    int arr[50];
    
    int en = 0;
    int te = 0;
    for(int i=0;i<n;i++)
    {
        cin>>arr[i];
    }
    sort(arr,arr+n);
    int temp=arr[k-1];// kth element is 
    for(int i = k;i<n;i++)//no of z after the k items
    {
        if(arr[i] == temp)
        {
            en++;
        }
    }
    if(en == 0)
    {
        cout<<"1";
        continue;
      
    }
    for(int i = k-2;i>=0;i--)//no of z inside the k items
    {
         if(arr[i] == temp)
        {
           te++;
        }
        
    }
    //calculating the factorial
    int total = en + te + 1;
    te++;
   
    long long int ans = total;
    if(te > total/2)
    {
        te=total-te;
    }
    for(int i=1;i<=te-1;i++)
    {
        ans=ans*(total-i)/(i+1);
    }
 cout<<ans<<endl;   
}
}

**Comment by dvkcool** [comment]
Hi there, welcome to competitive programming.
Firstly you have same logic as mine only instead of using max, you have used >l/2.

Second, instead of  `ans=ans*(total-i)/(i+1)` , use `ans=(ans*(total-i))/(i+1)`
Because of simple BODMAS.

Third if it still gives you wrong answer, use my code and yours, check for which input the answer is wrong (not manually, you can write a program to do so).
Then we can look for what's wrong.

However I think it's about BODMAS
